insert into integrante (franquia, nome, funcao) values ('DotA', 'Lucas', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('DotA', 'João', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Pedro', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Rodrigo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Marcelo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Pablo', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Marcos', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Guilherme', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Gabriel', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Felipe', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Renan', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Filipe', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Adilson', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Sergio', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Alexandre', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Toshio', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Zé', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Victor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Vitor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Luiz', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Israel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Caio', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Miguel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Arthur', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('DotA', 'Samuel', 'Posição 5')

insert into integrante (franquia, nome, funcao) values ('LoL', 'Lucas', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('LoL', 'João', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Pedro', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Rodrigo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Marcelo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Pablo', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Marcos', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Guilherme', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Gabriel', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Felipe', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Renan', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Filipe', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Adilson', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Sergio', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Alexandre', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Toshio', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Zé', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Victor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Vitor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Luiz', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Israel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Caio', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Miguel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Arthur', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('LoL', 'Samuel', 'Posição 5')

insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Lucas', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'João', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Pedro', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Rodrigo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Marcelo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Pablo', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Marcos', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Guilherme', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Gabriel', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Felipe', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Renan', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Filipe', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Adilson', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Sergio', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Alexandre', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Toshio', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Zé', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Victor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Vitor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Luiz', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Israel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Caio', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Miguel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Arthur', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Counter Strike', 'Samuel', 'Posição 5')

insert into integrante (franquia, nome, funcao) values ('Valorant', 'Lucas', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'João', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Pedro', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Rodrigo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Marcelo', 'Posição 1')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Pablo', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Marcos', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Guilherme', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Gabriel', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Felipe', 'Posição 2')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Renan', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Filipe', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Adilson', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Sergio', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Alexandre', 'Posição 3')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Toshio', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Zé', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Victor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Vitor', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Luiz', 'Posição 4')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Israel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Caio', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Miguel', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Arthur', 'Posição 5')
insert into integrante (franquia, nome, funcao) values ('Valorant', 'Samuel', 'Posição 5')
